### ISSUE TITLE
How do you install/use Scwilio?

### ISSUE THREAD

**Issue by mosesn** [daggerrz/Scwilio#8]
There aren't clear instructions.

**Comment by daggerrz** [comment]
Scwilio is a Scala API. It's artifacts are not published anywhere, so build them locally with SBT.

**Comment by daggerrz** [comment]
For actual examples on usage, look at the README at https://github.com/daggerrz/Scwilio

**Comment by mosesn** [comment]
I succeeded in building it with sbt, but am I supposed to put the class files in my library?  What are best practices with scwilio?

**Comment by daggerrz** [comment]
There are no best practices particular to Scwilio, but I'd suggest to drop the jar into your other project's lib folder as there are no versioned releases of Scwilio.
